ChangeAuth: Initial implementation.
Clap won't let us flatten both the `AuthInputArg` and `SecretOutputArg`
types in the `HsmCommand::ChangeAuth` variant because their member data
has naming conflicts. This is despite our explicit renaming w/ the
`long` `clap` derive attribute:

```
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.18/src/builder/debug_asserts.rs:86:13:
Command change-auth: Argument names must be unique, but 'method' is in use by more than one argument or group
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We want our auth value to end up w/ auth id 2. Before we do so we create
a well known auth value w/ auth id 1. We then create a new auth value,
burn it to CD, delete the old value w/ id 2, and then set the new auth
value.